# HAG HVAC Configuration
# Direct port from Rust configuration with Python-specific enhancements

hass_options:
  ws_url: "ws://homeassistant.local:8123/api/websocket"
  rest_url: "http://homeassistant.local:8123"
  token: "${HASS_TOKEN}"  # Set via environment variable
  max_retries: 5
  retry_delay_ms: 1000
  state_check_interval: 300000

hvac_options:
  temp_sensor: "sensor.indoor_temperature"
  outdoor_sensor: "sensor.openweathermap_temperature"
  system_mode: "auto"  # auto, heat_only, cool_only, off
  
  hvac_entities:
    - entity_id: "climate.hvac_system"
      enabled: true
      defrost: true
    
    - entity_id: "climate.bedroom_ac"
      enabled: false
      defrost: false

  heating:
    temperature: 21.0
    preset_mode: "comfort"
    temperature_thresholds:
      indoor_min: 19.7
      indoor_max: 20.2
      outdoor_min: -10.0
      outdoor_max: 15.0
    defrost:
      temperature_threshold: 0.0
      period_seconds: 3600
      duration_seconds: 300

  cooling:
    temperature: 24.0
    preset_mode: "eco"
    temperature_thresholds:
      indoor_min: 23.0
      indoor_max: 23.5
      outdoor_min: 10.0
      outdoor_max: 45.0

  active_hours:
    start: 8
    start_weekday: 7
    end: 22