# HAG HVAC Test Configuration
# Simplified configuration for testing

hass_options:
  ws_url: "ws://localhost:8123/api/websocket"
  rest_url: "http://localhost:8123"
  token: "test_token"
  max_retries: 3
  retry_delay_ms: 500
  state_check_interval: 300000

hvac_options:
  temp_sensor: "sensor.test_temperature"
  outdoor_sensor: "sensor.test_outdoor_temperature"
  system_mode: "auto"
  
  hvac_entities:
    - entity_id: "climate.test_ac"
      enabled: true
      defrost: false

  heating:
    temperature: 21.0
    preset_mode: "comfort"
    temperature_thresholds:
      indoor_min: 19.0
      indoor_max: 20.0
      outdoor_min: -10.0
      outdoor_max: 15.0
    defrost:
      temperature_threshold: 0.0
      period_seconds: 3600
      duration_seconds: 300

  cooling:
    temperature: 24.0
    preset_mode: "eco"
    temperature_thresholds:
      indoor_min: 23.0
      indoor_max: 25.0
      outdoor_min: 10.0
      outdoor_max: 40.0

  active_hours:
    start: 8
    start_weekday: 7
    end: 22